In [1]:
import pennylane as qml
from pennylane import numpy as np

In [2]:
dev = qml.device('default.qubit', shots=1000, wires=2, analytic=False)

In [3]:
def make_entanglement():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.probs(wires=[0, 1])

In [4]:
circuit = qml.QNode(make_entanglement, dev)

In [5]:
circuit()

tensor([0.487, 0.   , 0.   , 0.513], requires_grad=False)

In [6]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.probs(wires=[0, 1])

In [7]:
result = circuit()
print(result)

[0.506 0.    0.    0.494]


In [8]:
@qml.qnode(dev)
def circuit(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

circuit(np.pi/2)

tensor(-0.02, requires_grad=True)

In [9]:
@qml.qnode(dev)
def circuit(x):
    qml.RY(x, wires=0)
    return qml.expval(qml.PauliX(0))

circuit(np.pi/2)

tensor(1., requires_grad=True)

In [10]:
dev.shots = 5

In [11]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=1)
    return qml.sample(qml.PauliZ([1]))

circuit()

array([-1,  1, -1, -1, -1])

In [12]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=1)
    return qml.sample(qml.PauliX([1]))

circuit()

array([1, 1, 1, 1, 1])

In [13]:
U = np.array([[1, 0, 0, 0], 
              [0, 0, 1, 0], 
              [0, 1, 0, 0], 
              [0, 0, 0, 1]])

In [14]:
dev = qml.device('default.qubit', shots=1, wires=2, analytic=False)

In [15]:
@qml.qnode(dev)
def circuit(do_swap):
    qml.PauliX(wires=0)
    if do_swap:
        qml.QubitUnitary(U, wires=[0, 1])
    return qml.sample(qml.PauliZ([0])), qml.sample(qml.PauliZ([1]))

In [16]:
circuit(do_swap=False)

array([[-1],
       [ 1]])

In [17]:
circuit(do_swap=True)

array([[ 1],
       [-1]])

In [18]:
print(circuit.draw())

 0: ──X──╭U0──┤ Sample[Z] 
 1: ─────╰U0──┤ Sample[Z] 
U0 =
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]

